package mir.oslav.mockup.processor


/**
 * @since 1.0.0
 * @author Miroslav Hýbler <br>
 * created on 15.09.2023
 */
object MockupConstants {


    /**
     * TODO more info + link on issues
     * File header comment attached on the top of every generated file
     * @since 1.0.0
     */
    const val generatedFileHeader: String = "" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////\n" +
            "/////                                                                                               \n" +
            "/////\t\tFile generated by Mockup Library                                                           \n" +
            "/////\t\tAuthor Miroslav Hýbler                                                                     \n"+
            "/////                                                                                               \n" +
            "/////\t\tFor more information visit https://github.com/miroslavhybler/ksp-mockup                    \n" +
            "/////                                                                                               \n" +
            "////////////////////////////////////////////////////////////////////////////////////////////////////"
}