package mir.oslav.mockup.processor


/**
 * @since 1.0.0
 * @author Miroslav Hýbler <br>
 * created on 15.09.2023
 */
object MockupConstants {


    const val generatedFileHeader: String = "" +
            "////////////////////////////////////////////////////////////////////////////////////////////\n" +
            "/////                                                                                  /////\n" +
            "/////\tFile generated by Mockup Library                                                /////\n" +
            "/////\tAuthor Miroslav Hýbler\n                                                        /////\n"+
            "/////                                                                                  /////\n" +
            "/////\tFor more information visit https://github.com/miroslavhybler/ksp-mockup         /////\n" +
            "/////                                                                                  /////\n" +
            "////////////////////////////////////////////////////////////////////////////////////////////\n"
}